jobs: 100
keep-going: True
restart-times: 0
rerun-incomplete: True
max-jobs-per-second: 100
max-status-checks-per-second: 100
use-singularity: True
drmaa: "-p {resources.partition} -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} {resources.gres} -J {rule} -A wp4 -e slurm/{rule}_%j.err -o slurm/{rule}_%j.out --nodes=1-1"
default-resources: [gres="", ]
drmaa-log-dir: "slurm"
singularity-args: "--cleanenv --bind /beegfs-archive,/beegfs-scratch,/beegfs-storage,/scratch,/projects,/data,
$PWD/tmp:/tmp -B $PWD:$PWD -B /usr/lib/locale/:/usr/lib/locale/ --disable-cache --nv"
singularity-prefix: "/projects/wp4/nobackup/singularity_cache/"